# ==========================================================================
# Project:   SproutCore - JavaScript Application Framework
# Copyright: ©2008-2011 Apple Inc. All rights reserved.
# License:   Licensed under MIT license (see license.js)
# ==========================================================================


config :all, :required => :sproutcore, :url_prefix => "sc_docs", :load_fixtures => true
